const CREATE = 'CREATE';
const UPDATE = 'UPDATE';
const DELETE = 'DELETE';
const FETCH_ALL = 'FETCH_ALL';
const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
const FETCH_POST = 'FETCH_POST';
const LIKE = 'LIKE';
const COMMENT = 'COMMENT';
const FETCH_BY_CREATOR = 'FETCH_BY_CREATOR';

const AUTH = 'AUTH';
const LOGOUT = 'LOGOUT';

const START_LOADING = 'START_LOADING';
const END_LOADING = 'END_LOADING';

const CREATE_CARRIER = 'CREATE_CARRIER';
const UPDATE_CARRIER = 'UPDATE_CARRIER';
const DELETE_CARRIER = 'DELETE_CARRIER';
const FETCH_CARRIER_BY_SEARCH = 'FETCH_CARRIER_BY_SEARCH';
const FETCH_ALL_CARRIERS = 'FETCH_ALL_CARRIERS';
const FETCH_CARRIER = 'FETCH_CARRIER';

const CREATE_LOAD = 'CREATE_LOAD';
const UPDATE_LOAD = 'UPDATE_LOAD';
const DELETE_LOAD = 'DELETE_LOAD';
const FETCH_LOAD_BY_SEARCH = 'FETCH_LOAD_BY_SEARCH';
const FETCH_ALL_LOADS = 'FETCH_ALL_LOADS';
const FETCH_LOAD = 'FETCH_LOAD';

const CREATE_INVOICE = 'CREATE_INVOICE';
const UPDATE_INVOICE = 'UPDATE_INVOICE';
const DELETE_INVOICE = 'DELETE_INVOICE';
const FETCH_INVOICE_BY_SEARCH = 'FETCH_INVOICE_BY_SEARCH';
const FETCH_ALL_INVOICES = 'FETCH_ALL_INVOICES';
const FETCH_INVOICE = 'FETCH_INVOICE';

const FETCH_DRAFT = 'FETCH_DRAFT';

const CREATE_QUERY = 'CREATE_QUERY';
const UPDATE_QUERY = 'UPDATE_QUERY';
const DELETE_QUERY = 'DELETE_QUERY';
const FETCH_QUERY_BY_SEARCH = 'FETCH_QUERY_BY_SEARCH';
const FETCH_ALL_QUERIES = 'FETCH_ALL_QUERIES';
const FETCH_QUERY = 'FETCH_QUERY';

module.exports = {
  CREATE,
  UPDATE,
  DELETE,
  FETCH_ALL,
  FETCH_BY_SEARCH,
  FETCH_POST,
  LIKE,
  COMMENT,
  FETCH_BY_CREATOR,
  AUTH,
  LOGOUT,
  START_LOADING,
  END_LOADING,
  CREATE_CARRIER,
  UPDATE_CARRIER,
  DELETE_CARRIER,
  FETCH_CARRIER_BY_SEARCH,
  FETCH_ALL_CARRIERS,
  FETCH_CARRIER,
  CREATE_LOAD,
  UPDATE_LOAD,
  DELETE_LOAD,
  FETCH_LOAD_BY_SEARCH,
  FETCH_ALL_LOADS,
  FETCH_LOAD,
  CREATE_INVOICE,
  UPDATE_INVOICE,
  DELETE_INVOICE,
  FETCH_INVOICE_BY_SEARCH,
  FETCH_ALL_INVOICES,
  FETCH_INVOICE,
  FETCH_DRAFT,
  CREATE_QUERY,
  UPDATE_QUERY,
  DELETE_QUERY,
  FETCH_QUERY_BY_SEARCH,
  FETCH_ALL_QUERIES,
  FETCH_QUERY,
};