export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
export const FETCH_POST = 'FETCH_POST';
export const LIKE = 'LIKE';
export const COMMENT = 'COMMENT';
export const FETCH_BY_CREATOR = 'FETCH_BY_CREATOR';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';

export const CREATE_CARRIER = 'CREATE_CARRIER';
export const UPDATE_CARRIER = 'UPDATE_CARRIER';
export const DELETE_CARRIER = 'DELETE_CARRIER';
export const FETCH_CARRIER_BY_SEARCH = 'FETCH_CARRIER_BY_SEARCH';
export const FETCH_ALL_CARRIERS = 'FETCH_ALL_CARRIERS';
export const FETCH_CARRIER = 'FETCH_CARRIER';

export const CREATE_LOAD = 'CREATE_LOAD';
export const UPDATE_LOAD = 'UPDATE_LOAD';
export const DELETE_LOAD = 'DELETE_LOAD';
export const FETCH_LOAD_BY_SEARCH = 'FETCH_LOAD_BY_SEARCH';
export const FETCH_ALL_LOADS = 'FETCH_ALL_LOADS';
export const FETCH_LOAD = 'FETCH_LOAD';

export const CREATE_INVOICE = 'CREATE_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const FETCH_INVOICE_BY_SEARCH = 'FETCH_INVOICE_BY_SEARCH';
export const FETCH_ALL_INVOICES = 'FETCH_ALL_INVOICES';
export const FETCH_INVOICE = 'FETCH_INVOICE';

export const FETCH_DRAFT = 'FETCH_DRAFT';

export const CREATE_QUERY = 'CREATE_QUERY';
export const UPDATE_QUERY = 'UPDATE_QUERY';
export const DELETE_QUERY = 'DELETE_QUERY';
export const FETCH_QUERY_BY_SEARCH = 'FETCH_QUERY_BY_SEARCH';
export const FETCH_ALL_QUERIES = 'FETCH_ALL_QUERIES';
export const FETCH_QUERY = 'FETCH_QUERY';

